Create generate_FEMNIST.py
TsingZ0/PFLlib pull request #225
Opened 2024-12-09 18:20 UTC by jihyun-jeong-854

ADD FEMNIST Dataset
This code works after you download femnist dataset following instructions here:
[https://github.com/TalwalkarLab/leaf/blob/master/data/femnist/README.md](https://github.com/TalwalkarLab/leaf/blob/master/data/femnist/README.md)

Assume that the data is downloaded
./dataset/FEMNIST (same directory with mnist)

2024-12-10 02:31 UTC, TsingZ0 requested changes
- Could you include the data downloading code or a reminder note in this `.py` file?  
- It's recommended to rewrite the hyperparameter settings using `sys.argv`, consistent with other dataset generation scripts, instead of using `argparse`.

2024-12-10 14:10 UTC, jihyun-jeong-854 commented
Yes I updated!
Thank you

Best regards,
Jihyun Jeong

> On Dec 9, 2024, at 9:32 PM, Tsing ***@***.***> wrote:
> 
> 
> @TsingZ0 requested changes on this pull request.
> 
> Could you include the data downloading code or a reminder note in this .py file?
> It's recommended to rewrite the hyperparameter settings using sys.argv, consistent with other dataset generation scripts, instead of using argparse.
> —
> Reply to this email directly, view it on GitHub <https://github.com/TsingZ0/PFLlib/pull/225#pullrequestreview-2490696636>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AQGDU4SAXYYOV3W3SC3NG7D2EZHCFAVCNFSM6AAAAABTJNVSDWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDIOJQGY4TMNRTGY>.
> You are receiving this because you authored the thread.
>

2024-12-11 11:41 UTC, TsingZ0 approved these changes

2024-12-11 11:42 UTC, merged

2024-12-11 11:45 UTC, TsingZ0 commented
Great! Thank you for your efforts, which will greatly benefit the FL community 👍